site_name: Acceso a datos
site_url: https://bpaterna.github.io/acceso_datos2/
site_author: Begoña Paterna
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: cyan
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.expand
nav:
  - Presentación: index.md
  - Kotlin:
    - 1. Introducción: kotlin01.md
    - 2. Variables: kotlin02.md
  - Docker: docker.md
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
